name: logarte
description: Powerful in-app debug console for Flutter apps with network inspector, storage monitor, and password protection
version: 0.2.4
repository: https://github.com/kamranbekirovyz/logarte
issue_tracker: https://github.com/kamranbekirovyz/logarte/issues
homepage: https://bio.kamranbekirov.com
topics: [logger, debugger, logging]

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: