name: logarte
description: In-app debug console and logger for Flutter to monitor the app on-air
version: 0.1.6
repository: https://github.com/kamranbekirovyz/logarte
issue_tracker: https://github.com/kamranbekirovyz/logarte/issues
homepage: https://bio.kamranbekirov.com
topics: [logger, debugger, logging]

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  stack_trace: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: